name: mediroo
description: MediRoo Application

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.0.1
  cloud_firestore: ^0.7.3
  firebase_core: ^0.2.2
  firebase_analytics: ^1.0.3
  firebase_messaging: ^1.0.5
  firebase_auth: ^0.5.12
  flutter_local_notifications: ^0.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is included
  uses-material-design: true

  # Application assets
  assets:
    - logo.png
    - wi-sunrise.png
    - wi-sun.png
    - wi-sunset.png
    - wi-night.png
    - wi-day-sunny.png
    - wi-sunset.png
    - wi-night-clear.png
    - full-logo.png
    - sun.png
    - sunrise.png
    - sunset.png
    - moon.png
    - check.png
    - cross.png
